source 'https://rubygems.org'

gem 'connection_pool'
gem 'json'
gem 'redis'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-contrib'

# tracing
gem 'ddtrace', :git => 'https://github.com/DataDog/dd-trace-rb.git', :ref => '3ccbf914d71d7865fe094c7cdb55dba965e4684c'
