source 'https://rubygems.org'

gem 'connection_pool'
gem 'json'
gem 'redis'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-contrib'

# tracing
gem 'ddtrace', :git => 'https://github.com/DataDog/dd-trace-rb.git', :ref => '5c6695b8272f35868deef9c54371f24670d65d79'
